services:
  - type: web
    name: mplad-fraudshield
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python demo_prep.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./mplad_demo.db
      - key: GEMINI_API_KEY
        sync: false
      - key: APP_ENV
        value: production
    disk:
      name: mplad-data
      mountPath: /opt/render/project/src/backend
      sizeGB: 1